// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: TrueNorth

#include "ui.h"

lv_obj_t * uic_MotionLeftButton;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_PropSwitch = NULL;
lv_obj_t * ui_Prop_Label = NULL;
lv_obj_t * ui_MotionLabel = NULL;
lv_obj_t * ui_MotionSwitch = NULL;
lv_obj_t * ui_MotionLeftButton = NULL;
lv_obj_t * ui_LeftMotionLabel = NULL;
lv_obj_t * ui_MotionRightButton = NULL;
lv_obj_t * ui_RightMotionLabel = NULL;
lv_obj_t * ui_TrueNorthLabel = NULL;
lv_obj_t * ui_Lights_Label = NULL;
lv_obj_t * ui_LighsSwitch = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x3A3A3A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PropSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_PropSwitch, 50);
    lv_obj_set_height(ui_PropSwitch, 25);
    lv_obj_set_x(ui_PropSwitch, -80);
    lv_obj_set_y(ui_PropSwitch, -25);
    lv_obj_set_align(ui_PropSwitch, LV_ALIGN_CENTER);

    ui_Prop_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Prop_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Prop_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Prop_Label, -85);
    lv_obj_set_y(ui_Prop_Label, -62);
    lv_obj_set_align(ui_Prop_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Prop_Label, "Prop");
    lv_obj_set_style_text_color(ui_Prop_Label, lv_color_hex(0x8ACCDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Prop_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Prop_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotionLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_MotionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MotionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MotionLabel, 74);
    lv_obj_set_y(ui_MotionLabel, -59);
    lv_obj_set_align(ui_MotionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MotionLabel, "Motion");
    lv_obj_set_style_text_color(ui_MotionLabel, lv_color_hex(0x1DD288), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MotionLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotionSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_MotionSwitch, 50);
    lv_obj_set_height(ui_MotionSwitch, 25);
    lv_obj_set_x(ui_MotionSwitch, 73);
    lv_obj_set_y(ui_MotionSwitch, -26);
    lv_obj_set_align(ui_MotionSwitch, LV_ALIGN_CENTER);

    ui_MotionLeftButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_MotionLeftButton, 68);
    lv_obj_set_height(ui_MotionLeftButton, 50);
    lv_obj_set_x(ui_MotionLeftButton, 34);
    lv_obj_set_y(ui_MotionLeftButton, 32);
    lv_obj_set_align(ui_MotionLeftButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MotionLeftButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MotionLeftButton, lv_color_hex(0xF3FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MotionLeftButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MotionLeftButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotionLeftButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftMotionLabel = lv_label_create(ui_MotionLeftButton);
    lv_obj_set_width(ui_LeftMotionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LeftMotionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LeftMotionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LeftMotionLabel, "<");
    lv_obj_set_style_text_color(ui_LeftMotionLabel, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LeftMotionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LeftMotionLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MotionRightButton = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_MotionRightButton, 68);
    lv_obj_set_height(ui_MotionRightButton, 50);
    lv_obj_set_x(ui_MotionRightButton, 118);
    lv_obj_set_y(ui_MotionRightButton, 32);
    lv_obj_set_align(ui_MotionRightButton, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MotionRightButton, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_MotionRightButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MotionRightButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RightMotionLabel = lv_label_create(ui_MotionRightButton);
    lv_obj_set_width(ui_RightMotionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RightMotionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RightMotionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RightMotionLabel, ">");
    lv_obj_set_style_text_color(ui_RightMotionLabel, lv_color_hex(0x1F1F1F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RightMotionLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RightMotionLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TrueNorthLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TrueNorthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TrueNorthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TrueNorthLabel, -2);
    lv_obj_set_y(ui_TrueNorthLabel, -101);
    lv_obj_set_align(ui_TrueNorthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TrueNorthLabel, "True North Control");
    lv_obj_set_style_text_color(ui_TrueNorthLabel, lv_color_hex(0xE7E5E5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TrueNorthLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TrueNorthLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Lights_Label = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Lights_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lights_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lights_Label, -81);
    lv_obj_set_y(ui_Lights_Label, 36);
    lv_obj_set_align(ui_Lights_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lights_Label, "Lights");
    lv_obj_set_style_text_color(ui_Lights_Label, lv_color_hex(0x8ACCDD), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Lights_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Lights_Label, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LighsSwitch = lv_switch_create(ui_Screen1);
    lv_obj_set_width(ui_LighsSwitch, 50);
    lv_obj_set_height(ui_LighsSwitch, 25);
    lv_obj_set_x(ui_LighsSwitch, -80);
    lv_obj_set_y(ui_LighsSwitch, 73);
    lv_obj_set_align(ui_LighsSwitch, LV_ALIGN_CENTER);

    uic_MotionLeftButton = ui_MotionLeftButton;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_PropSwitch = NULL;
    ui_Prop_Label = NULL;
    ui_MotionLabel = NULL;
    ui_MotionSwitch = NULL;
    uic_MotionLeftButton = NULL;
    ui_MotionLeftButton = NULL;
    ui_LeftMotionLabel = NULL;
    ui_MotionRightButton = NULL;
    ui_RightMotionLabel = NULL;
    ui_TrueNorthLabel = NULL;
    ui_Lights_Label = NULL;
    ui_LighsSwitch = NULL;

}
