// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.6
// Project name: TrueNorth

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_PropSwitch;
extern lv_obj_t * ui_Prop_Label;
extern lv_obj_t * ui_MotionLabel;
extern lv_obj_t * ui_MotionSwitch;
extern lv_obj_t * ui_MotionLeftButton;
extern lv_obj_t * ui_LeftMotionLabel;
extern lv_obj_t * ui_MotionRightButton;
extern lv_obj_t * ui_RightMotionLabel;
extern lv_obj_t * ui_TrueNorthLabel;
extern lv_obj_t * ui_Lights_Label;
extern lv_obj_t * ui_LighsSwitch;
// CUSTOM VARIABLES
extern lv_obj_t * uic_MotionLeftButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

